name: Release Chirp (.NET 8, single-file)

on:
  push:
    tags:
      - 'v*'         # fx v0.1.0, v1.2.3

permissions:
  contents: write   

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: Chirp.Cli/Chirp.Cli.csproj
      APP_NAME: chirp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true

      - name: Restore
        run: dotnet restore

      - name: Build + Test (Release)
        run: |
          dotnet build --configuration Release --no-restore
          dotnet test  --configuration Release --no-build --verbosity normal

      - name: Publish single-file for Win/Mac/Linux (RID loop)
        run: |
          set -euxo pipefail
          rids=("win-x64" "osx-x64" "linux-x64")
          for rid in "${rids[@]}"; do
            out="publish/$rid"
            dotnet publish "$PROJECT_PATH" \
              -c Release \
              -r "$rid" \
              -o "$out" \
              -p:PublishSingleFile=true \
              -p:SelfContained=false \
              -p:IncludeNativeLibrariesForSelfExtract=true \
              --no-restore
            # Navngiv binær
            bin="$APP_NAME"
            [[ "$rid" == "win-x64" ]] && bin="$APP_NAME.exe"
            # Pak som zip uden mappe-træ
            (cd "$out" && zip -q -9 -j "../../${APP_NAME}-${rid}.zip" "$bin")
          done
          ls -lah publish


      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: |
            publish/${{ env.APP_NAME }}-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
