name: Label issues
on:
  issues:
    types: [opened, reopened]

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Ensure label exists
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh label create "triage" --color FEF2C0 --description "Needs triage" \
            || echo "Label already exists"

      - name: Add label
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
        run: |
          gh issue edit "$NUMBER" --add-label "triage"
